export const SWITCH_TEMPERATURE_UNIT = 'SWITCH_TEMPERATURE_UNIT';

export const GET_CURRENT_COORDS_REQUEST = 'GET_CURRENT_COORDS_REQUEST';
export const GET_CURRENT_COORDS_SUCCESS = 'GET_CURRENT_COORDS_SUCCESS';
export const GET_CURRENT_COORDS_ERROR = 'GET_CURRENT_COORDS_ERROR';

export const FETCH_CURRENT_WEATHER_REQUEST = 'FETCH_CURRENT_WEATHER_REQUEST';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';
export const FETCH_CURRENT_WEATHER_ERROR = 'FETCH_CURRENT_WEATHER_ERROR';

export const FETCH_CITY_WEATHER_REQUEST = 'FETCH_CITY_WEATHER_REQUEST';
export const FETCH_CITY_WEATHER_SUCCESS = 'FETCH_CITY_WEATHER_SUCCESS';
export const FETCH_CITY_WEATHER_ERROR = 'FETCH_CITY_WEATHER_ERROR';

export const FETCH_CITY_WEATHER_MAP_REQUEST = 'FETCH_CITY_WEATHER_MAP_REQUEST';
export const FETCH_CITY_WEATHER_MAP_SUCCESS = 'FETCH_CITY_WEATHER_MAP_SUCCESS';
export const FETCH_CITY_WEATHER_MAP_ERROR = 'FETCH_CITY_WEATHER_MAP_ERROR';

export const FETCH_CITY_WEATHER_FORECAST_REQUEST = 'FETCH_CITY_WEATHER_FORECAST_REQUEST';
export const FETCH_CITY_WEATHER_FORECAST_SUCCESS = 'FETCH_CITY_WEATHER_FORECAST_SUCCESS';
export const FETCH_CITY_WEATHER_FORECAST_ERROR = 'FETCH_CITY_WEATHER_FORECAST_ERROR';

export const FETCH_WEATHER_FORECAST_COMPARE_REQUEST = 'FETCH_WEATHER_FORECAST_COMPARE_REQUEST';
export const FETCH_WEATHER_FORECAST_COMPARE_SUCCESS = 'FETCH_WEATHER_FORECAST_COMPARE_SUCCESS';
export const FETCH_WEATHER_FORECAST_COMPARE_ERROR = 'FETCH_WEATHER_FORECAST_COMPARE_ERROR';

export const DELETE_CITY_WEATHER_CARD = 'DELETE_CITY_WEATHER_CARD';

export const CHANGE_SEQUENCE_WEATHER_LIST = 'CHANGE_SEQUENCE_WEATHER_LIST';

export const ADD_GRAPH_FORECAST_TEMP_MEMO = 'ADD_GRAPH_FORECAST_TEMP_MEMO';
